name: Deploy to Maven Central

# on:
#   # Runs on pushes targeting the default branch
#   push:
#     branches: ["main"]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
jobs:
  # Single deploy job since we're just deploying
  deploy-maven:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: üì¶Download build artificat
        uses: actions/download-artifact@v3
        with:
          name: scaffi-framework-build
      - name: üçµSet up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.2'
          distribution: 'oracle'
          cache: 'maven'
      - name: üçµPublish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}